create type coordinate as object
(x number, y number);
--
drop table streets;
create table streets
(
id_street number generated by default on null as identity,
name_street varchar2(100),
first_x number,
first_y number,
second_x number,
second_y number,
p1 coordinate,
p2 coordinate
);
--
drop table wifipoints;
create table wifipoints(
id_point number generated by default on null as identity,
name_point varchar2(100),
radius number,
x number,
y number,
p coordinate
);