create type coordinate as object
(
  x number,
  y number
)
;
--
drop table streets;
/ create table streets(id_street number generated by default on null as identity, name_street varchar2(100), first_x number, first_y number, second_x number, second_y number, p1 coordinate, p2 coordinate);
/
--
drop table wifipoints;
/ create table wifipoints(id_point number generated by default on null as identity, name_point varchar2(100), radius number, x number, y number, p coordinate);
/
--
drop table tmp_tbl_for_graph;
/ 
create global temporary table tmp_tbl_for_graph(id number, from_street number, to_street number, p1x number, p1y number, p2x number, p2y number, cost_flow number, wifi number) on commit delete rows;
/
--
drop table tmp_tbl_for_calc;
/ 
--
create global temporary table tmp_tbl_for_calc(id number, d number, s number, cons number) on commit delete rows;
/ 
--
drop type ways_t; 
--
create type ways_t as object(from_x number, from_y number, to_x number, to_y number, wifi number); 
--
drop type ways_tbl; 
--
create type ways_tbl is table of ways_t;